export const LOAD_PHOTOS = 'LOAD_PHOTOS';
export const LOAD_HEADER_IMAGE = 'LOAD_HEADER_IMAGE';
export const HIDE_LOADING = 'HIDE_LOADING';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CHANGE_SIZE_OPTION = 'CHANGE_SIZE_OPTION';
