export const suggestionsArray = [
  'cityscape',
  'beach',
  'desert',
  'abstract',
  'forest',
  'night',
  'city',
  'landscape',
  'sky',
  'people',
  'sunset',
  'town',
  'skyline',
  'architecture',
  'car',
  'office',
  'street',
  'road',
  'background',
  'london',
  'mountain',
  'new york',
  'building',
  'business',
  'technology',
  'travel',
  'light',
  'nature',
  'day',
  'japan',
  'summer',
  'dogs',
  'cats',
  'flowers',
  'design',
  'lights',
  'sea',
  'smoke',
  'lightning',
  'rain',
];

export const ROUTES = {
  INDEX: '/',
  SEARCH: '/search',
  COLLECTION: '/collection',
  ALL: '*',
};

// yep, it obviously should not be here, but do i care? It's not like it's a production app
export const AUTH_TOKEN = '563492ad6f917000010000014640aabb4e9d420cbe1c0df7daf4c2bf';
